- lib/subprocess.rb
- lib/subprocess/version.rb
While using `Subprocess.check_output` with the `cwd:` option, I encountered this exception:
```
17:28:58 /var/lib/gems/2.1.0/gems/subprocess-1.3.0/lib/subprocess.rb:253:in `block in initialize': uninitialized constant Subprocess::Process::FileUtils (NameError)
17:28:58 	from /var/lib/gems/2.1.0/gems/subprocess-1.3.0/lib/subprocess.rb:251:in `fork'
17:28:58 	from /var/lib/gems/2.1.0/gems/subprocess-1.3.0/lib/subprocess.rb:251:in `initialize'
17:28:58 	from /var/lib/gems/2.1.0/gems/subprocess-1.3.0/lib/subprocess.rb:85:in `new'
17:28:58 	from /var/lib/gems/2.1.0/gems/subprocess-1.3.0/lib/subprocess.rb:85:in `check_output'
17:28:58 	from /pay/jenkins/stripe/scripts/postprocess-coverage.rb:68:in `main'
17:28:58 	from /pay/jenkins/stripe/scripts/postprocess-coverage.rb:73:in `<main>'
```
Line …
> Add missing require of fileutils

- lib/subprocess.rb
- lib/subprocess/version.rb
- test/test_subprocess.rb
Subprocess always returns output strings encoded as ASCII-8BIT even if
the IO uses a different encoding. `read_nonblock` really can't do
anything else since it's reading raw bytes and might split up Unicode
characters. Instead, we need to set the encoding of the complete
string after we're done receiving it. `external_encoding` isn't
readable on closed IOs so we have to read that at the beginning of
`communicate`.
> Handle non-ASCII output from commands

- lib/subprocess.rb
- lib/subprocess/version.rb
We've had several reports of people running OS X getting an `EAGAINWaitWritable` error from Subprocess writing to stdin. Rebooting the machine seems to fix the issue. On a non-rebooted machine, I was able to verify that after writing 512 bytes to a new pipe, subsequent writes would throw an error even immediately after `select` indicated that the fd is writable:
```
>> data = "a" * 819;
>> r, w = IO.pipe;
>> IO.select([], [w])
[[], [#<IO:fd 11>], []]
>> w.write_nonblock(data)
512
>> IO.select([], [w])
[[], [#<IO:fd 11>], []]
>> w.write_nonblock(data)
<raises EAGAINWaitWritable>
>> IO.select([], [w])
[[], [#<IO:fd 11>], []]
```
I was also able to confirm that this diff fixes the observed issue and the Subprocess completes cleanly.
There's some precedent for making this change:
* As far as …
> Don't treat WaitWritable on stdin as an error

- lib/subprocess.rb
- lib/subprocess/version.rb
- test/test_subprocess.rb
Subprocess a bug in which it can fail to read data buffered in pipes
after the process terminates. It currently attempts to handle this
case by calling `drain_fd` on each ready fd after detecting that the
process has exited by calling `poll`. If the process writes to the
pipe between the `select` and the `poll`, we won't attempt to read
from that pipe. This can happen if the process write to stderr, then
writes to stdout and then exits. `select` will return after the write
to stderr then the child writes to stdout and exits and then we poll.
I think there's also an edge case where the process receives an
interupt in `drain_fd` after the child has exited and catches EINTR.
Instead we should continue looping until we've received EOF or EPIPE from
each of the read pipes except the self_pipe. …
> Fix the exit condition for Subprocess

- lib/subprocess.rb
- test/test_subprocess.rb
If you call #communicate on a process with no open pipes, and the
process exits before we enter the `catching_sigchld` block, we would
deadlock forever waiting on a SIGCHLD that would never arrive.
Arguably calling `#communicate` on a process with no open pipes should
be an error, but it's arguably useful as a synonym for `#wait` if you
don't know whether or not there's output, and I'm wary of breaking
clients.
r? @evan-stripe 
cc @andrew-stripe
> Fix a deadlock in #communicate

- lib/subprocess.rb
- test/test_subprocess.rb
Currently when you supply an invalid cmd or env you get a generic TypeError from inside some Ruby C code that gives you no indication of what you did wrong. This wraps those exceptions in a message that at least tells you what argument you messed up.
r? @nelhage
> Provide helpful messages for invalid cmd and env arguments

- lib/subprocess.rb
It's not at present entirely clear how this can happen; My best theory
involves forking-with-active-threads, which is unsafe in other
ways. However, this patch seems ~clearly correct; If the reader has
gone away for whatever reason, it should be safe to drop the wakeup.
r? @andrew-stripe
> Handle EPIPE in handle_sigchld.

- lib/subprocess.rb
- lib/subprocess/version.rb
This switches from calling FileUtils.cd (an alias for Dir.chdir) to using the block form of Dir.chdir. Unless you use the block form, invoking Subprocess with the cwd option within another chdir block triggers a warning message on the console from:
https://github.com/ruby/ruby/blob/v2_4_1/dir.c#L1033-L1034
I recommend reviewing with `?w=1` since this is almost all whitespace change.
r? @nelhage 
cc @stripe/product-infra
> Use block form of Dir.chdir

- lib/subprocess.rb
- lib/subprocess/version.rb
- test/test_subprocess.rb
Note to reviewers: The first commit here is a straight revert of #29. I'd suggest reviewing only the second commit (note that commit bumps the version two numbers because the revert rolled it back).
Using `FileUtils.cd` (an alias for `Dir.chdir`) triggers a warning message when Subprocess is called with the cwd arg from inside another chdir block:
https://github.com/ruby/ruby/blob/v2_4_1/dir.c#L1033-L1034
In #29, I tried fixing this by using the block form of `Dir.chdir` but that caused many people to see errors of the form:
```
<elided>/subprocess-1.3.7/lib/subprocess.rb:280:in `exec': Too many open files - getcwd (Errno::EMFILE)
```
Instead of calling `chdir` in Ruby, I think it makes more sense to pass `chdir` as an argument to exec.
I still have to call `Dir.chdir` around a …
> Fix Errno::EMFILE with cwd caused by #29

- lib/subprocess.rb
- lib/subprocess/version.rb
- test/test_subprocess.rb
This adds an optional `timeout_s` parameter to communicate that causes it to time out after some number of seconds. This is useful in handling processes that can hang under certain conditions. For example, you might want to timeout after a certain time and then call `terminate` to kill the process.
r? @russell-stripe 
cc @stripe/product-infra @zenazn
> Add a timeout parameter to `communicate`

- lib/subprocess.rb
- lib/subprocess/version.rb
This enables us to properly grab the `@sigchld_mutex` and synchronize
with writers.
It turns out that signal handlers execute on the main thread and may
interleave with other writers. This manifested as `handle_sigchld`
`write`ing to pipes that had already been closed (by the `IO.pipe`)
block, resulting in nasty exceptions.
By grabbing the lock, we ensure that we serialize reading the list of
wakeup pipes properly with respect to writers.
r? @andrew-stripe
> Wakeup SIGCHLD listeners on a separate thread.

- lib/subprocess.rb
- lib/subprocess/version.rb
- test/test_subprocess.rb
It can be useful to read partial output from a long running process before it completes (e.g. to provide feedback to the user about the progress). This adds the ability to pass a block to `communicate` that gets called with data read from stdout/stderr as its read instead of returning it.
r? @nelhage
> Add support for partial reads from Subprocess#communicate

- lib/subprocess.rb
- lib/subprocess/version.rb
This extra thread is causing issues with our CI infrastructure, which
makes assertions that tests don't leak threads.
Instead, create a single self-pipe that the signal handler writes
into; All `communicate` loops read from that pipe and then grab the
mutex and rebroadcast the wakeup. Since they're running in normal
threads, they can safely synchronize.
r? @andrew-stripe
> Don't spawn a thread from inside the signal handler.

- lib/subprocess.rb
- lib/subprocess/version.rb
If we `fork`, it's important that the child and parent don't share a self-read pipe, since if they do, they risk stealing each others' events.
Check the PID and re-create the pipe if it's changed. This is theoretically subject to PID-wraparound issues, but should work well enough.
r? @andrew-stripe
> Make the global self-read pipe `fork`-safe

- lib/subprocess.rb
- lib/subprocess/version.rb
- test/test_subprocess.rb
Currently we only exit the `communicate` loop when we get an EOF from stdout and stderr. If the child process forks before exiting, the fork will inherit those file descriptors and `communicate` will hang until the child exits. I believe it's preferable to drain stdout/stderr after the process exits and then break out of the `communicate` loop.
Note that Open3 similarly hangs waiting for EOF. There is a risk that existing software depends on this behavior and that output could be non-deterministic if the forked grandchild is writing to stdout/stderr. Do you think that's acceptable?
r? @nelhage-stripe
> Do not hang in communicate if spawned process forks

- lib/subprocess.rb
- test/test_subprocess.rb
Handle encoding of output from `Process#communicate` identically whether a block is provided or not.
`Process#communicate` depends on Ruby's `IO#read_nonblock` via `Process#drain_fd`. Strings returned from `read_nonblock` are handled as `ASCII-8BIT` to prevent data loss. (For a demonstration of this behavior, download and run [this snippet](https://gist.github.com/andrew-breunig/69a1a6ffc5a1dbefa8d08dcd643bc912).) If output from a subprocess has a different encoding, this can lead to decoding errors.
When not provided a block, `Process#communicate` handles this by [capturing encoding settings](https://github.com/stripe/subprocess/blob/master/lib/subprocess.rb#L405-L406) at the beginning of the method and [re-applying these settings](https://github.com/stripe/subprocess/blob/master/lib/subp …
> Apply captured encoding settings on output from partial reads in Process#communicate

- lib/subprocess.rb
- test/test_subprocess.rb
Preserve encoding of output from `Process#communicate` with no block given across multiple cycles of `IO` selection.
The previous PR #57 on this repository changed the way that [encoding is preserved](lib/subprocess.rb) by `Process#communicate`, so that output yielded to a block would preserve encoding similarly to returned output when no block is given. Tests included in that branch demonstrated that encoding was still preserved [with no block given](https://github.com/stripe/subprocess/pull/57/files#diff-8d8364001adacc8504929848d85ca56dR351) within a single `IO` write cycle, but failed to account for cases where no block is given **and** the subprocess writes across multiple cycles of `IO` selection.
Under those conditions, the previous changes introduce a new failure mode in which …
> Apply captured encoding to returned output across IO selection cycles

- lib/subprocess.rb
- test/test_subprocess.rb
`Subprocess#communicate` does not handle Unicode data correctly when the input intended for the child's stdin is more than the `write_nonblock` limit (pipe size). Unicode input may have multi-byte characters, which don't play well with how Subprocess currently keeps track of which data still need to be written to child's stdin:
https://github.com/stripe/subprocess/blob/master/lib/subprocess.rb#L499
In particular `Encoding::UTF_8` strings will see dropped or corrupted data beyond the first pipe size boundary.
This change calls `force_encoding` on all input passed to stdin so that assumptions baked into the byte slicing logic still hold.
I've added a unit test that reproduces the issue and verified that the change fixes it.
> subprocess: handle binary/unicode input to stdin

- lib/subprocess.rb
Authored-by @synfo-stripe
Without this change communicating 700MB worth of data to 'cat' takes
~1h, with it it's closer to 1s.
My hypothesis is that `input[0...written] = ''` causes ruby to either
allocate a whole new string buffer, or at the very least rewrite the
entirety of the existing buffer, whereas `input = input[written..]` lets
ruby use shared string optimization and only create a new RString
pointing to the same buffer.
> Make Process#communicate do less work on every iteration

- Gemfile
- Rakefile
- lib/subprocess.rb
- lib/subprocess/version.rb
- subprocess.gemspec
- test/test_subprocess.rb
While running tests for https://github.com/sorbet/sorbet/pull/7778 I noticed some deprecation warnings coming from this gem.
Ruby 3.4 will have chilled string literals, as a first step toward frozen string literals becoming the default.
Ref: https://bugs.ruby-lang.org/issues/20205
> Convert the gem to frozen string literals

- .github/workflows/ruby.yml
CI is failing on Ruby 2.5 and it's giga old.
> Remove support for Ruby 2.5
